# Generated by Django 6.0.3 on 2026-04-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='vector_store_file_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
