# Generated by Django 6.0.3 on 2026-04-08 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_document_vector_store_file_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='vector_store_file_id',
        ),
    ]
